name: Auto Update Apple IDs

on:
  schedule:
    # 更改为每 10 分钟自动执行一次
    - cron: '*/10 * * * *'
  workflow_dispatch: # 仍保留手动触发按钮

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run update script
      run: python update_accounts.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add get-apple-id.md
        git diff-index --quiet HEAD || git commit -m "docs: auto update shared accounts"
        git push
